print("Ingresa el numero:")
n = input()

operando = int(n)

print("{} x 1 = {}".format(operando, operando))
print("{} x 2 = {}".format(operando, operando * 2))
print("{} x 3 = {}".format(operando, operando * 3))
print("{} x 4 = {}".format(operando, operando * 4))
print("{} x 5 = {}".format(operando, operando * 5))
print("{} x 6 = {}".format(operando, operando * 6))
print("{} x 7 = {}".format(operando, operando * 7))
print("{} x 8 = {}".format(operando, operando * 8))
print("{} x 9 = {}".format(operando, operando * 9))
print("{} x 10 = {}".format(operando, operando * 10))
